### ISSUE TITLE
Example from section 2 results in SIGSEGV

### ISSUE THREAD

**Issue by evaporei** [ToshioCP/Gobject-tutorial#6]
Hello! First and foremost thanks for the tutorial you've made, it's helping me to understand how to use the GObject library (and how it works).

I tried running the second example in [section 2](https://toshiocp.github.io/Gobject-tutorial/sec2.html) locally, and ran into an SIGSEGV (Address boundary error).

```c
#include <glib-object.h>

static void
show_ref_count (GObject *instance) {
  if (G_IS_OBJECT (instance))
    /* Users should not use ref_count member in their program. */
    /* This is only for demonstration. */
    g_print ("Reference count is %d.\n", instance->ref_count);
  else
    g_print ("Instance is not GObject.\n");
}

int
main (int argc, char **argv) {
  GObject *instance;
  
  instance = g_object_new (G_TYPE_OBJECT, NULL);
  g_print ("Call g_object_new.\n");
  show_ref_count (instance);
  g_object_ref (instance);
  g_print ("Call g_object_ref.\n");
  show_ref_count (instance);
  g_object_unref (instance);
  g_print ("Call g_object_unref.\n");
  show_ref_count (instance);
  g_object_unref (instance);
  g_print ("Call g_object_unref.\n");
  show_ref_count (instance);
  
  return 0;
}
```

I've used `gdb` and the problem is at the last line `show_ref_count (instance)` after the instance has been freed. It doesn't even get into the function `show_ref_count` nor the `G_IS_OBJECT` call, it fails before at `g_type_check_instance_is_fundamentally_a` which I would guess happens when the instance pointer is copied into a function? :thinking: I'm not sure how that happens.

I don't know either if it's any problem with my local environment. In your page you mention that there are examples in the `misc` folder, but I couldn't find those [here](https://download.gnome.org/sources/glib/).

I'm using an Arch Linux and compiling via `gcc` with the following command:

```bash
gcc -g example.c -o example $(pkg-config --cflags --libs gobject-2.0)
```

If it is the case that my environment is correct and this error is reproducible, how does one check that an `GObject *` instance is null without calling any function using it? :thinking:

**Comment by evaporei** [comment]
Update: I just saw you have the source for the examples under this repo, I compiled using your `meson` + `ninja` commands and had the same issue:

```
Call g_object_new.
Reference count is 1.
Call g_object_ref.
Reference count is 2.
Call g_object_unref.
Reference count is 1.
Call g_object_unref.
fish: Job 1, './_build/example2' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ToshioCP** [comment]
Thank you for posting the issue, Eva.
The error comes from the bug in the program `src/example2`.
It accesses the same adress that was allocated for the GObject nstance.
Since the instance has destroyed and the memories have been returned to the system, the access is illegal and causes the error.
So, I changed the program and removed the illegal access.
See `src/misc/example2.c`.

By the way, I'd like to add something about the relation between `src` directory and `gfm` directory.
The directory `gfm` includes all the markdown file to which the readers can see by following the link in the `Readme.md` file.
They are generated by:

```console
$ rake
```

The source files are under the `src` directory.
So, if you want to update the markdown files, you should modify the corresponding source file and run `rake`.
For further information, see <https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/Readme_for_developers.md>.
Gtk4-tutorial and GObject-tutorial have the same generation program.

Anyway, thank you very much for your help.

Toshio Sekiya

**Comment by evaporei** [comment]
I see, that makes sense, still as a user of the GLib/GObject library, how do I check that an `GObject *` instance has been freed? It seems from that example that just calling a function with such a pointer causes a Segmentation Fault.

**Comment by ToshioCP** [comment]
I think it's impossible to know whether the GObject instance has been destroyed or not.
And you don't need to know whether it has been destroyed and the memory is freed.

The destruction begins automatically when the reference count becomes zero.
So, you don't need to free GObject instances by yourself.

We often say the caller of `g_object_new` or `g_object_ref` owns the instance. (=> increase the reference count)
The owner must call `g_object_unref` and release the instance when it is useless. (=> decrease the reference count)
This makes the remaining reference count comes from other objects.
If all of them release the instance, the reference count will be zero and the instance destruction process will begin automatically.

Reference counting is one of the memory management systems.
C program language doesn't have garbage collection system, so this reference counting is important.

I don't think my explanation is good, but memory management is one of the difficult topics.
If you have another question, feel free to ask me again.

Toshio Sekiya
